version: 2.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_cache
      - test:
          requires:
            - build_cache
      - publish:
          context: org-global
          requires:
            - test
          filters:
            branches:
              only: master

jobs:
  build_cache:
    docker:
      - image: clojure:latest
    working_directory: /code/
    steps:
      - checkout
      - restore_cache:
         keys:
           - deps-v0.0.0-{{ checksum "project.clj" }}

      - run:
          name: Download dependencies
          command: lein deps

      - save_cache:
          key: deps-v0.0.0-{{ checksum "project.clj" }}
          paths:
            - /root/.m2

  test:
    docker:
      - image: clojure:latest
    working_directory: /code/
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v0.0.0-{{ checksum "project.clj" }}

      - run:
          name: Run Tests
          command: lein cci-test
          environment:
            CLJ_DEPS__GH__ORG: AlexanderMann
            # CLJ_DEPS__GH__TOKEN: <present in project env vars>

      - store_test_results:
          path: target/test-results

      - store_artifacts:
          path: target/test-results
          destination: raw-test-output

      - store_artifacts:
          path: storage
          destination: clj-deps-output

  publish:
    docker:
      - image: stongo/command-convenience:0.2.0
        environment:
          CONTAINER_ORG: mannimal
          NAME: clj-deps
          DOCKERFILE_PATH: Dockerfile
          DOCKER_REGISTRY: dockerhub
    working_directory: /code/
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-v0.0.0-{{ checksum "project.clj" }}

      - setup_remote_docker

      - run:
          command: publish
